server:
  port: 9004
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liyong561/algorithm/
          # 搜寻路径，可能根据文件名来搜索，也可能是其他的匹配方法，当然也可以使用本地文件系统，就是换了一个路径名，使用native
          searchPaths: config-file
